apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-upf-configmap
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration

    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      ReportCaller: false

      # packetBufferHoldTime should be longer than Paging retry-out time of AMF.
      # unit: seconds
      packetBufferHoldTime: 30

      pfcp:
        # - addr: upf.free5gc.org
        - addr: free5gc-upf-svc

      gtpu:
        # - addr: upf.free5gc.org
        - addr: free5gc-upf-svc
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif

      dnn_list:
        - dnn: internet
          cidr: 10.60.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-upf-svc
spec:
  selector:
    app: free5gc-upf
  clusterIP: None # 10.96.100.10
  ports:
    - name: pfcp
      protocol: UDP
      port: 8805
    - name: sbi
      port: 29518
      protocol: TCP
    - name: gtp
      protocol: UDP
      port: 2152
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
    spec:
      # hostNetwork: true
      containers:
      - name: free5gc-upf-container
        image: everynamehavebeenuse/free5gc_user:3.1.1
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "sleep 5s && /setup-uptun.sh eth0 && ./bin/free5gc-upfd"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: upfcfg
          mountPath: /free5gc/NFs/upf/build/config/upfcfg.yaml
          subPath: upfcfg.yaml
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: upfcfg
        configMap:
          name: free5gc-upf-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml